Repository chaaard/CSI-UI-Prod, pull requests merged in 2024-06, with the labels that each got.

#17 phase2 logs bugfixing
  src/Components/Common/HeaderButtons.tsx
  src/Components/Common/ManualReload.tsx
  src/Components/Common/ManualTransfer.tsx
  src/Components/Common/UploadProoflist.tsx
  src/Components/Functions/InsertLogs.ts
  src/Context/AuthProvider.tsx
  src/Pages/Auth/Login.tsx
  src/Pages/Common/Interface/IAnalyticsProps.ts
  src/Pages/Common/Interface/IRefreshAnalytics.ts
  src/Pages/CustomerCode/CustomerCode.tsx
  src/Pages/CustomerCode/Interface/ICustomerUpdateDelete.ts
  src/Pages/Reports/Exception/Exceptions.tsx
  src/Pages/Reports/GeneratedInvoice/GeneratedInvoice.tsx
  src/Pages/Reports/WeeklyDelivery/WeeklyDelivery.tsx
  src/Pages/Treasury/FoodPanda/FoodPanda.tsx
  src/Pages/Treasury/GCash/GCash.tsx
  src/Pages/Treasury/GrabFood/GrabFood.tsx
  src/Pages/Treasury/GrabMart/GrabMart.tsx
  src/Pages/Treasury/MetroMart/MetroMart.tsx
  src/Pages/Treasury/PickARooFS/PickARooFS.tsx
  src/Pages/Treasury/PickARooMerch/PickARooMerch.tsx
Labels: bug, enhancement

#18 Additional Features
  src/Components/Common/ModalComponent.tsx
  src/Pages/Auth/Login.tsx
  src/Pages/Common/Interface/IFirstLogin.ts
  src/Pages/DashboardUsers/DashboardUsers.tsx
  src/Pages/DashboardUsers/Interface/IDashboardUsers.ts
  src/Pages/DashboardUsers/Interface/IUsersUpdateInsert.ts
  src/Route/Router.tsx
Labels: bug, enhancement

#21 Minor changes
  src/Components/Common/ManualAdd.tsx
  src/Components/Common/Users.tsx
  src/Components/SideNav.tsx
  src/Pages/CustomerCode/CustomerCode.tsx
  src/Pages/DashboardMaintenance/DashboardMaintenance.tsx
  src/Pages/DashboardMaintenance/Interface/IDashboardUsers.ts
  src/Pages/DashboardMaintenance/Interface/IUsersUpdateInsert.ts
  src/Pages/DashboardUsers/DashboardUsers.tsx
  src/Route/Router.tsx
  tsconfig.json
Labels: bug, enhancement

#23 Csi UI prod merchant 3
  src/Pages/Treasury/BankPromos/BankPromos.tsx
  src/Pages/Treasury/Employee/Employee.tsx
  src/Pages/Treasury/GCash/GCash.tsx
  src/Pages/Treasury/VolumeShopper/VolumeShopper.tsx
  src/Pages/Treasury/WalkIn/WalkIn.tsx
Labels: enhancement

#27 Update Dashboard.tsx
  src/Pages/DashboardTreasury/Dashboard.tsx
Labels: bug

#28 Enhancement
  src/Pages/_SystemAdmin/Merchants/Merchants.tsx
  src/Pages/_SystemAdmin/Stores/Stores.tsx
  src/Pages/_SystemAdmin/Users/Users.tsx
Labels: bug, enhancement

#29 origin/enhancement-240618
  src/Components/Common/ModalComponent.tsx
  src/Components/SideNav.tsx
  src/Pages/_SystemAdmin/Logs/Interface/ILogDetails.ts
  src/Pages/_SystemAdmin/Logs/Interface/ILogs.ts
  src/Pages/_SystemAdmin/Logs/Logs.tsx
  src/Pages/_SystemAdmin/Merchants/Merchants.tsx
  src/Pages/_SystemAdmin/Stores/Stores.tsx
  src/Pages/_SystemAdmin/Users/Users.tsx
  src/Route/Router.tsx
Labels: bug, enhancement

#30 Minor UI Enhancement
  src/Components/Common/AccountingGenerateInvoice.tsx
  src/Components/Common/AccountingMatchTable.tsx
  src/Components/Common/AnalyticsTable.tsx
  src/Components/Common/MatchTable.tsx
  src/Components/Common/PaperComponent.tsx
  src/Components/Common/PaymentTable.tsx
  src/Components/Common/PortalTable.tsx
  src/Components/Common/SalesTransactionTable.tsx
  src/Components/Common/UploadProoflist.tsx
  src/Pages/DashboardAccounting/DashboardAccounting.tsx
  src/Pages/DashboardTreasury/Dashboard.tsx
  src/Pages/Reports/Exception/Exceptions.tsx
  src/Pages/Reports/GeneratedInvoice/GeneratedInvoice.tsx
  src/Pages/Reports/WeeklyDelivery/WeeklyDelivery.tsx
  src/Pages/_Accounting/FoodPanda/FoodPanda.tsx
  src/Pages/_Accounting/GrabFood/GrabFood.tsx
  src/Pages/_Accounting/GrabMart/GrabMart.tsx
  src/Pages/_Accounting/MetroMart/MetroMart.tsx
  src/Pages/_Accounting/PickARooFS/PickARooFS.tsx
  src/Pages/_Accounting/PickARooMerch/PickARooMerch.tsx
  src/Pages/_SystemAdmin/Analytics/ManualAdd/ManualAdd.tsx
  src/Pages/_SystemAdmin/Analytics/ManualReload/ManualReload.tsx
  src/Pages/_SystemAdmin/Analytics/ManualTransferDelete/ManualTransfer.tsx
  src/Pages/_SystemAdmin/Analytics/ManualUndoSubmit/UndoSubmit.tsx
  src/Pages/_SystemAdmin/Merchants/Merchants.tsx
  src/Pages/_SystemAdmin/Stores/Stores.tsx
  src/Pages/_SystemAdmin/Users/Users.tsx
  src/Pages/_Treasury/FoodPanda/FoodPanda.tsx
  src/Pages/_Treasury/GrabFood/GrabFood.tsx
  src/Pages/_Treasury/GrabMart/GrabMart.tsx
  src/Pages/_Treasury/MetroMart/MetroMart.tsx
  src/Pages/_Treasury/PickARooFS/PickARooFS.tsx
  src/Pages/_Treasury/PickARooMerch/PickARooMerch.tsx
Labels: bug, enhancement

#31 Enhancements
  src/Components/Common/DisputeTable.tsx
  src/Components/Common/ExceptionsTable.tsx
  src/Components/Common/UploadProoflist.tsx
  src/Pages/Common/Interface/ICategory.ts
  src/Pages/Reports/Exception/Exceptions.tsx
  src/Pages/_SystemAdmin/Analytics/ManualAdd/ManualAdd.tsx
  src/Pages/_SystemAdmin/Analytics/ManualTransferDelete/ManualTransfer.tsx
  src/Pages/_SystemAdmin/Merchants/Interface/IMerchants.ts
  src/Pages/_SystemAdmin/Merchants/Interface/IMerchantsUpdateDelete.ts
  src/Pages/_SystemAdmin/Merchants/Merchants.tsx
  src/Pages/_Treasury/GrabMart/GrabMart.tsx
Labels: bug, enhancement

#32 Origin/enhancement 240618
  src/Pages/Common/Interface/IVarianceMMS.ts
  src/Pages/DashboardTreasury/Dashboard.tsx
  src/Pages/_SystemAdmin/Logs/Logs.tsx
Labels: enhancement

#34 Csi UI prod merchant 3
  src/Components/Common/AccountingGenerateInvoice.tsx
  src/Components/Common/AdjustmentTypeModal.tsx
  src/Components/Common/BoxHeaderButtons.tsx
  src/Components/Common/CustomerDropdown.tsx
  src/Components/Common/DisputeAnalytics.tsx
  src/Components/Common/ExceptionsTable.tsx
  src/Components/Common/HeaderButtons.tsx
  src/Components/Common/IncorrectJOFields.tsx
  src/Components/Functions/GetTotalAmountPerMechant.ts
  src/Components/Functions/GetTotalAmountTransactions.ts
  src/Pages/Common/Interface/ICustomerDropdown.ts
  src/Pages/Common/Interface/IExceptionMerchant.ts
  src/Pages/Common/Interface/IPagination.ts
  src/Pages/DashboardTreasury/Dashboard.tsx
  src/Pages/Reports/Exception/Exceptions.tsx
  src/Pages/Reports/GeneratedInvoice/GeneratedInvoice.tsx
  src/Pages/Reports/WeeklyDelivery/WeeklyDelivery.tsx
  src/Pages/_SystemAdmin/Analytics/ManualAdd/ManualAdd.tsx
  src/Pages/_SystemAdmin/Analytics/ManualReload/ManualReload.tsx
  src/Pages/_SystemAdmin/Analytics/ManualTransferDelete/ManualTransfer.tsx
  src/Pages/_SystemAdmin/Analytics/ManualUndoSubmit/UndoSubmit.tsx
  src/Pages/_SystemAdmin/Merchants/Interface/IMerchants.ts
  src/Pages/_SystemAdmin/Merchants/Merchants.tsx
  src/Pages/_Treasury/BankPromos/BankPromos.tsx
  src/Pages/_Treasury/Employee/Employee.tsx
  src/Pages/_Treasury/FoodPanda/FoodPanda.tsx
  src/Pages/_Treasury/GCash/GCash.tsx
  src/Pages/_Treasury/GCash/backup/GCash.tsx
  src/Pages/_Treasury/GrabFood/GrabFood.tsx
  src/Pages/_Treasury/GrabMart/GrabMart.tsx
  src/Pages/_Treasury/Lazada/Lazada.tsx
  src/Pages/_Treasury/MetroMart/MetroMart.tsx
  src/Pages/_Treasury/PickARooFS/PickARooFS.tsx
  src/Pages/_Treasury/PickARooMerch/PickARooMerch.tsx
  src/Pages/_Treasury/VolumeShopper/VolumeShopper.tsx
  src/Pages/_Treasury/WalkIn/WalkIn.tsx
  src/Route/Router.tsx
Labels: enhancement

#35 UI
  src/Components/Common/DisputeAnalytics.tsx
  src/Components/Common/ModalComponent.tsx
  src/Pages/_SystemAdmin/Analytics/ManualAdd/ManualAdd.tsx
  src/Pages/_SystemAdmin/Analytics/ManualReload/ManualReload.tsx
  src/Pages/_Treasury/BankPromos/BankPromos.tsx
  src/Pages/_Treasury/Employee/Employee.tsx
  src/Pages/_Treasury/FoodPanda/FoodPanda.tsx
  src/Pages/_Treasury/GCash/GCash.tsx
  src/Pages/_Treasury/GrabFood/GrabFood.tsx
  src/Pages/_Treasury/GrabMart/GrabMart.tsx
  src/Pages/_Treasury/MetroMart/MetroMart.tsx
  src/Pages/_Treasury/PickARooFS/PickARooFS.tsx
  src/Pages/_Treasury/PickARooMerch/PickARooMerch.tsx
  src/Pages/_Treasury/VolumeShopper/VolumeShopper.tsx
  src/Pages/_Treasury/WalkIn/WalkIn.tsx
Labels: enhancement

#36 Csi UI prod merchant 3
  src/Components/Common/AdjustmentTypeModal.tsx
  src/Components/Common/ExceptionsTable.tsx
  src/Components/Common/HeaderButtons.tsx
  src/Components/Common/ModalComponent.tsx
  src/Pages/_Treasury/BankPromos/BankPromos.tsx
  src/Pages/_Treasury/Employee/Employee.tsx
  src/Pages/_Treasury/GCash/GCash.tsx
  src/Pages/_Treasury/GrabMart/GrabMart.tsx
  src/Pages/_Treasury/VolumeShopper/VolumeShopper.tsx
  src/Pages/_Treasury/WalkIn/WalkIn.tsx
Labels: enhancement
