Repository chaaard/CSI-UI-Prod, pull requests merged in 2024-08, with the labels that each got.

#53 Uat bugs/enhancements 72624
  src/Components/Common/AccountingAdjustmentTypeModal.tsx
  src/Components/Common/AccountingAdjustmentsTable.tsx
  src/Components/Common/AccountingChronology.tsx
  src/Components/Common/AccountingMatchTable.tsx
  src/Components/Common/AccountingViewChargeableFields.tsx
  src/Components/Common/ModalComponent.tsx
  src/Components/Common/PortalTable.tsx
  src/Components/Common/UploadProoflist.tsx
  src/Components/SideNav.tsx
  src/Pages/Common/Interface/IAccountingAdjustmentsView.ts
  src/Pages/Common/Interface/IAccountingChronology.ts
  src/Pages/Reports/Exception/Exceptions.tsx
  src/Pages/Reports/PaymentRecon/PaymentReconReport.tsx
  src/Pages/Reports/WeeklyDelivery/WeeklyDelivery.tsx
  src/Pages/_Accounting/FoodPanda/FoodPanda.tsx
  src/Pages/_Accounting/GrabFood/GrabFood.tsx
  src/Pages/_Accounting/GrabMart/GrabMart.tsx
  src/Pages/_Accounting/MetroMart/MetroMart.tsx
  src/Pages/_Accounting/PickARooFS/PickARooFS.tsx
  src/Pages/_Accounting/PickARooMerch/PickARooMerch.tsx
  src/Route/Router.tsx
Labels: bug, enhancement

#55 Update Report
  src/Components/SideNav.tsx
  src/Pages/Common/Interface/IAccountingBalancesDetails.ts
  src/Pages/Reports/BalancesDetailsReport/BalancesDetailsReport.tsx
  src/Route/Router.tsx
Labels: bug, enhancement

#56 Modifications of Submit All, Reports, Invoice Generation
  src/Components/Common/AccountingGenerateInvoice.tsx
  src/Components/Common/CustomerDropdown.tsx
  src/Components/Common/ModalComponent.tsx
  src/Components/SideNav.tsx
  src/Pages/Common/Interface/IAnalyticsProps.ts
  src/Pages/Common/Interface/IPagination.ts
  src/Pages/Common/Interface/IRefreshAnalytics.ts
  src/Pages/Common/Interface/IUBRenewalReport.ts
  src/Pages/Common/Interface/IVarianceMMS.ts
  src/Pages/DashboardTreasury/Dashboard.tsx
  src/Pages/Reports/UBRenewalReport/UBRenewalReport.tsx
  src/Pages/Reports/UBVoucherReport/UBVoucherReport.tsx
  src/Pages/Reports/UnionBankInvoice/UnionBankInvoice.tsx
  src/Route/Router.tsx
Labels: enhancement

#57 Csi UI 8 1 2024
  src/Components/Common/BoxHeaderButtons.tsx
  src/Components/Common/HeaderButtons.tsx
  src/Components/SideNav.tsx
  src/Pages/DashboardTreasury/Dashboard.tsx
Labels: enhancement

#58 Csi UI 8 1 2024
  src/Pages/DashboardTreasury/Dashboard.tsx
Labels: enhancement

#59 Csi UI 8 1 2024
  src/Pages/DashboardTreasury/Dashboard.tsx
  src/Pages/Reports/GeneratedInvoiceReport/GeneratedInvoiceReport.tsx
Labels: enhancement

#62 UI enhancements 8122024
  src/Components/Common/AccountingMatchPaymentTable.tsx
  src/Components/Common/AccountingMatchTable.tsx
  src/Components/Common/AdjustmentTypeModal.tsx
  src/Components/ReusableComponents/ButtonComponents/StyledAdjustmentButton.tsx
  src/Pages/DashboardTreasury/Dashboard.tsx
Labels: bug, enhancement

#63 Update Others.tsx
  src/Pages/Treasury/Others/Others.tsx
Labels: bug

#64 Update GeneratedInvoiceReport.tsx
  src/Pages/Reports/GeneratedInvoiceReport/GeneratedInvoiceReport.tsx
Labels: bug, enhancement

#65 Csi UI 8 1 2024
  src/Components/SideNav.tsx
  src/Pages/Treasury/Others/Others.tsx
  src/Pages/Treasury/WalkIn/WalkIn.tsx
  src/Route/Router.tsx
Labels: enhancement

#67 UI enhancements 8132024
  src/Components/Common/AccountingMatchTable.tsx
  src/Components/Common/AnalyticsTable.tsx
  src/Components/Common/MatchTable.tsx
  src/Components/Common/PaymentTable.tsx
  src/Components/Common/PortalTable.tsx
  src/Components/Common/SalesTransactionTable.tsx
  src/Components/ReusableComponents/TableComponents/StyledTableCellTotal.tsx
Labels: enhancement

#68 Update UI
  src/Components/Common/AccountingAdjustmentsTable.tsx
  src/Components/Common/AccountingMatchTable.tsx
  src/Components/Common/UploadProoflist.tsx
Labels: enhancement

#69 Csi UI 8 1 2024
  src/Pages/DashboardTreasury/Dashboard.tsx
  src/Pages/SystemAdmin/Analytics/ManualReload/ManualReload.tsx
Labels: enhancement

#71 update again
  src/Components/Common/PaymentReconCards.tsx
  src/Pages/DashboardAccounting/DashboardAccounting.tsx
Labels: bug, enhancement

#72 Csi UI 8 1 2024
  src/Pages/Reports/ExceptionReport/ExceptionsReport.tsx
  src/Pages/Treasury/Others/Others.tsx
Labels: enhancement

#74 Confirmation Update
  src/Components/Common/IncorrectJOFields.tsx
  src/Components/Common/IncorrectPartnerFields.tsx
  src/Pages/SystemAdmin/Analytics/ManualTransferDelete/ManualTransfer.tsx
Labels: bug, enhancement

#75 Update FloatingCSI.tsx
  src/Pages/Treasury/FloatingCSI/FloatingCSI.tsx
Labels: bug, enhancement
